// ============================================================
// INSAN — i18n / Language strings
// Supported: en, hi, ur, fa (+ ar, fr, de, es, tr, zh, pt — label only)
// ============================================================

const LANG = {

  /* ── English ─────────────────────────────────────────────── */
  en: {
    dir: 'ltr',
    appName:            'Insan',
    login:              'Login',
    signup:             'Sign Up',
    welcomeBack:        'Welcome back to Insan',
    joinInsan:          'Join Insan today',
    fullName:           'Full Name',
    username:           'Username',
    email:              'Email',
    password:           'Password',
    confirmPassword:    'Confirm Password',
    forgotPassword:     'Forgot password?',
    noAccount:          "Don't have an account?",
    haveAccount:        'Already have an account?',
    chats:              'Chats',
    channels:           'Channels',
    groups:             'Groups',
    typeMessage:        'Type a message…',
    send:               'Send',
    online:             'Online',
    offline:            'Last seen recently',
    typing:             'typing…',
    noChats:            'No chats yet',
    noChatsDesc:        'Search for users to start a conversation',
    noMessages:         'No messages yet',
    noMessagesDesc:     'Say hello!',
    editProfile:        'Edit Profile',
    bio:                'Bio',
    save:               'Save',
    cancel:             'Cancel',
    close:              'Close',
    createChannel:      'Create Channel',
    createGroup:        'Create Group',
    channelName:        'Channel Name *',
    groupName:          'Group Name *',
    description:        'Description',
    searchByName:       'Search by name…',
    searchUsers:        'Search by @username or name…',
    settings:           'Settings',
    notifications:      'Push Notifications',
    enablePush:         'Enable Push Notifications',
    tapToGrant:         'Tap to grant OS permission',
    msgPreview:         'Message Preview',
    msgPreviewSub:      'Show message content in notification',
    vibration:          'Vibration',
    vibrationSub:       'Vibrate on incoming messages & calls',
    testNotif:          'Test Notification',
    testNotifSub:       "Send a test push to verify it's working",
    calls:              'Calls',
    callRingtone:       'Call Ringtone',
    callVibrate:        'Call Vibration',
    callVibrateSub:     'Vibrate on incoming calls',
    chat_settings:      'Chat',
    enterSend:          'Send with Enter',
    enterSendSub:       'Press Enter to send messages',
    readReceipts:       'Read Receipts',
    readReceiptsSub:    'Show when messages are read',
    typingIndicator:    'Typing Indicator',
    typingIndicatorSub: 'Show when you are typing',
    autoDownload:       'Auto-Download Media',
    autoDownloadSub:    'Automatically download images and files',
    privacy:            'Privacy',
    lastSeen:           'Last Seen',
    lastSeenSub:        'Who can see your last seen',
    profilePhoto:       'Profile Photo',
    profilePhotoSub:    'Who can see your profile photo',
    whoCanMsg:          'Who Can Message Me',
    whoCanMsgSub:       'Restrict who can start a conversation',
    security:           'Security & Account',
    changePassword:     'Change Password',
    changePasswordSub:  'Update your account password',
    twoFactor:          'Two-Factor Authentication',
    twoFactorSub:       'Extra layer of account security',
    appLock:            'App Lock',
    appLockSub:         'Protect app with a 4-digit PIN',
    blockedUsers:       'Blocked Users',
    blockedUsersSub:    'Manage blocked accounts',
    deleteAccount:      'Delete My Account',
    deleteAccountSub:   'Permanently remove all your data',
    data:               'Data & Storage',
    bgData:             'Background Data',
    bgDataSub:          'Always on — messages & calls received in background',
    bgSync:             'Background Sync',
    bgSyncSub:          'Always on — syncs when app is closed or backgrounded',
    account:            'Account',
    logout:             'Logout',
    logoutSub:          'Sign out of your account',
    language:           'Language',
    languageSub:        'App display language',
    appearance:         'Appearance',
    theme:              'Theme',
    fontSize:           'Font Size',
    newPassword:        'New Password',
    update:             'Update',
    today:              'Today',
    yesterday:          'Yesterday',
    noResults:          'No users found',
    startChat:          'Start Chat',
    profileUpdated:     'Profile updated!',
    passwordMismatch:   'Passwords do not match',
    usernameRequired:   'Username is required',
    fillAllFields:      'Please fill all fields',
    userNotFound:       'User not found',
    somethingWrong:     'Something went wrong',
    accountCreated:     'Account created! Please log in.',
    search:             'Search',
    flowPlaceholder:    "What's on your mind?",
    writeComment:       'Write a comment…',
    activeSessions:     'Active Sessions',
    changePIN:          'Change PIN',
    darkMode:           'Dark Mode',
    lightMode:          'Light Mode',
  },

  /* ── Hindi ───────────────────────────────────────────────── */
  hi: {
    dir: 'ltr',
    appName:            'इंसान',
    login:              'लॉगिन',
    signup:             'साइन अप',
    welcomeBack:        'इंसान में वापस स्वागत है',
    joinInsan:          'आज इंसान से जुड़ें',
    fullName:           'पूरा नाम',
    username:           'उपयोगकर्ता नाम',
    email:              'ईमेल',
    password:           'पासवर्ड',
    confirmPassword:    'पासवर्ड की पुष्टि करें',
    forgotPassword:     'पासवर्ड भूल गए?',
    noAccount:          'अकाउंट नहीं है?',
    haveAccount:        'पहले से अकाउंट है?',
    chats:              'चैट',
    channels:           'चैनल',
    groups:             'ग्रुप',
    typeMessage:        'संदेश लिखें…',
    send:               'भेजें',
    online:             'ऑनलाइन',
    offline:            'हाल ही में दिखे',
    typing:             'टाइप कर रहे हैं…',
    noChats:            'अभी कोई चैट नहीं',
    noChatsDesc:        'बातचीत शुरू करने के लिए उपयोगकर्ता खोजें',
    noMessages:         'अभी कोई संदेश नहीं',
    noMessagesDesc:     'नमस्ते कहें!',
    editProfile:        'प्रोफ़ाइल संपादित करें',
    bio:                'बायो',
    save:               'सहेजें',
    cancel:             'रद्द करें',
    close:              'बंद करें',
    createChannel:      'चैनल बनाएं',
    createGroup:        'ग्रुप बनाएं',
    channelName:        'चैनल का नाम *',
    groupName:          'ग्रुप का नाम *',
    description:        'विवरण',
    searchByName:       'नाम से खोजें…',
    searchUsers:        '@उपयोगकर्ता नाम या नाम से खोजें…',
    settings:           'सेटिंग्स',
    notifications:      'पुश नोटिफिकेशन',
    enablePush:         'पुश नोटिफिकेशन चालू करें',
    tapToGrant:         'OS अनुमति के लिए टैप करें',
    msgPreview:         'संदेश पूर्वावलोकन',
    msgPreviewSub:      'नोटिफिकेशन में संदेश सामग्री दिखाएं',
    vibration:          'कंपन',
    vibrationSub:       'संदेश और कॉल पर कंपन करें',
    testNotif:          'टेस्ट नोटिफिकेशन',
    testNotifSub:       'जांचने के लिए एक टेस्ट नोटिफिकेशन भेजें',
    calls:              'कॉल',
    callRingtone:       'कॉल रिंगटोन',
    callVibrate:        'कॉल कंपन',
    callVibrateSub:     'इनकमिंग कॉल पर कंपन करें',
    chat_settings:      'चैट',
    enterSend:          'Enter से भेजें',
    enterSendSub:       'संदेश भेजने के लिए Enter दबाएं',
    readReceipts:       'पठन रसीदें',
    readReceiptsSub:    'दिखाएं कि संदेश कब पढ़े गए',
    typingIndicator:    'टाइपिंग संकेतक',
    typingIndicatorSub: 'दिखाएं जब आप टाइप कर रहे हों',
    autoDownload:       'मीडिया ऑटो-डाउनलोड',
    autoDownloadSub:    'चित्र और फ़ाइलें स्वचालित रूप से डाउनलोड करें',
    privacy:            'गोपनीयता',
    lastSeen:           'अंतिम बार देखा',
    lastSeenSub:        'कौन आपका अंतिम बार देखा देख सकता है',
    profilePhoto:       'प्रोफ़ाइल फ़ोटो',
    profilePhotoSub:    'कौन आपकी प्रोफ़ाइल फ़ोटो देख सकता है',
    whoCanMsg:          'मुझे कौन संदेश कर सकता है',
    whoCanMsgSub:       'बातचीत शुरू करने पर प्रतिबंध लगाएं',
    security:           'सुरक्षा और अकाउंट',
    changePassword:     'पासवर्ड बदलें',
    changePasswordSub:  'अपना अकाउंट पासवर्ड अपडेट करें',
    twoFactor:          'दो-कारक प्रमाणीकरण',
    twoFactorSub:       'अकाउंट सुरक्षा की अतिरिक्त परत',
    appLock:            'ऐप लॉक',
    appLockSub:         '4-अंकीय PIN से ऐप सुरक्षित करें',
    blockedUsers:       'अवरुद्ध उपयोगकर्ता',
    blockedUsersSub:    'अवरुद्ध अकाउंट प्रबंधित करें',
    deleteAccount:      'मेरा अकाउंट हटाएं',
    deleteAccountSub:   'सभी डेटा स्थायी रूप से हटाएं',
    data:               'डेटा और स्टोरेज',
    bgData:             'बैकग्राउंड डेटा',
    bgDataSub:          'हमेशा चालू — बैकग्राउंड में संदेश और कॉल',
    bgSync:             'बैकग्राउंड सिंक',
    bgSyncSub:          'हमेशा चालू — ऐप बंद होने पर सिंक करें',
    account:            'अकाउंट',
    logout:             'लॉगआउट',
    logoutSub:          'अपने अकाउंट से साइन आउट करें',
    language:           'भाषा',
    languageSub:        'ऐप प्रदर्शन भाषा',
    appearance:         'दिखावट',
    theme:              'थीम',
    fontSize:           'फ़ॉन्ट आकार',
    newPassword:        'नया पासवर्ड',
    update:             'अपडेट करें',
    today:              'आज',
    yesterday:          'कल',
    noResults:          'कोई उपयोगकर्ता नहीं मिला',
    startChat:          'चैट शुरू करें',
    profileUpdated:     'प्रोफ़ाइल अपडेट हो गई!',
    passwordMismatch:   'पासवर्ड मेल नहीं खाते',
    usernameRequired:   'उपयोगकर्ता नाम आवश्यक है',
    fillAllFields:      'कृपया सभी फ़ील्ड भरें',
    userNotFound:       'उपयोगकर्ता नहीं मिला',
    somethingWrong:     'कुछ गलत हो गया',
    accountCreated:     'अकाउंट बन गया! कृपया लॉगिन करें।',
    search:             'खोज',
    flowPlaceholder:    'आपके मन में क्या है?',
    writeComment:       'टिप्पणी लिखें…',
    activeSessions:     'सक्रिय सत्र',
    changePIN:          'PIN बदलें',
    darkMode:           'डार्क मोड',
    lightMode:          'लाइट मोड',
  },

  /* ── Urdu ────────────────────────────────────────────────── */
  ur: {
    dir: 'rtl',
    appName:            'انسان',
    login:              'لاگ ان',
    signup:             'سائن اپ',
    welcomeBack:        'انسان میں خوش آمدید',
    joinInsan:          'آج انسان سے جڑیں',
    fullName:           'پورا نام',
    username:           'صارف نام',
    email:              'ای میل',
    password:           'پاس ورڈ',
    confirmPassword:    'پاس ورڈ کی تصدیق کریں',
    forgotPassword:     'پاس ورڈ بھول گئے؟',
    noAccount:          'اکاؤنٹ نہیں ہے؟',
    haveAccount:        'پہلے سے اکاؤنٹ ہے؟',
    chats:              'چیٹس',
    channels:           'چینلز',
    groups:             'گروپس',
    typeMessage:        'پیغام لکھیں…',
    send:               'بھیجیں',
    online:             'آن لائن',
    offline:            'حال ہی میں نظر آئے',
    typing:             'ٹائپ کر رہے ہیں…',
    noChats:            'ابھی کوئی چیٹ نہیں',
    noChatsDesc:        'گفتگو شروع کرنے کے لیے صارفین تلاش کریں',
    noMessages:         'ابھی کوئی پیغام نہیں',
    noMessagesDesc:     'سلام کریں!',
    editProfile:        'پروفائل ترمیم کریں',
    bio:                'بایو',
    save:               'محفوظ کریں',
    cancel:             'منسوخ',
    close:              'بند کریں',
    createChannel:      'چینل بنائیں',
    createGroup:        'گروپ بنائیں',
    channelName:        'چینل کا نام *',
    groupName:          'گروپ کا نام *',
    description:        'تفصیل',
    searchByName:       'نام سے تلاش کریں…',
    searchUsers:        '@صارف نام یا نام سے تلاش کریں…',
    settings:           'ترتیبات',
    notifications:      'پش نوٹیفیکیشنز',
    enablePush:         'پش نوٹیفیکیشن فعال کریں',
    tapToGrant:         'OS اجازت کے لیے ٹیپ کریں',
    msgPreview:         'پیغام پیش نظارہ',
    msgPreviewSub:      'نوٹیفیکیشن میں پیغام دکھائیں',
    vibration:          'وائبریشن',
    vibrationSub:       'پیغامات اور کالز پر وائبریٹ کریں',
    testNotif:          'ٹیسٹ نوٹیفیکیشن',
    testNotifSub:       'تصدیق کے لیے ٹیسٹ نوٹیفیکیشن بھیجیں',
    calls:              'کالز',
    callRingtone:       'کال رنگ ٹون',
    callVibrate:        'کال وائبریشن',
    callVibrateSub:     'آنے والی کالز پر وائبریٹ کریں',
    chat_settings:      'چیٹ',
    enterSend:          'Enter سے بھیجیں',
    enterSendSub:       'پیغام بھیجنے کے لیے Enter دبائیں',
    readReceipts:       'پڑھنے کی رسید',
    readReceiptsSub:    'دکھائیں کہ پیغام کب پڑھے گئے',
    typingIndicator:    'ٹائپنگ اشارہ',
    typingIndicatorSub: 'دکھائیں جب آپ ٹائپ کر رہے ہوں',
    autoDownload:       'میڈیا آٹو ڈاؤنلوڈ',
    autoDownloadSub:    'تصاویر اور فائلیں خود بخود ڈاؤنلوڈ کریں',
    privacy:            'رازداری',
    lastSeen:           'آخری بار آن لائن',
    lastSeenSub:        'کون آپ کا آخری بار آن لائن دیکھ سکتا ہے',
    profilePhoto:       'پروفائل تصویر',
    profilePhotoSub:    'کون آپ کی پروفائل تصویر دیکھ سکتا ہے',
    whoCanMsg:          'مجھے کون پیغام کر سکتا ہے',
    whoCanMsgSub:       'گفتگو شروع کرنے پر پابندی لگائیں',
    security:           'سیکیورٹی اور اکاؤنٹ',
    changePassword:     'پاس ورڈ تبدیل کریں',
    changePasswordSub:  'اپنا اکاؤنٹ پاس ورڈ اپڈیٹ کریں',
    twoFactor:          'دو عنصری تصدیق',
    twoFactorSub:       'اکاؤنٹ سیکیورٹی کی اضافی پرت',
    appLock:            'ایپ لاک',
    appLockSub:         '4 ہندسوں کے PIN سے ایپ محفوظ کریں',
    blockedUsers:       'بلاک کردہ صارفین',
    blockedUsersSub:    'بلاک کردہ اکاؤنٹس منظم کریں',
    deleteAccount:      'میرا اکاؤنٹ حذف کریں',
    deleteAccountSub:   'تمام ڈیٹا مستقل طور پر ہٹائیں',
    data:               'ڈیٹا اور اسٹوریج',
    bgData:             'بیک گراؤنڈ ڈیٹا',
    bgDataSub:          'ہمیشہ چالو — بیک گراؤنڈ میں پیغامات اور کالز',
    bgSync:             'بیک گراؤنڈ سنک',
    bgSyncSub:          'ہمیشہ چالو — ایپ بند ہونے پر سنک کریں',
    account:            'اکاؤنٹ',
    logout:             'لاگ آؤٹ',
    logoutSub:          'اپنے اکاؤنٹ سے سائن آؤٹ کریں',
    language:           'زبان',
    languageSub:        'ایپ ڈسپلے زبان',
    appearance:         'ظاہری شکل',
    theme:              'تھیم',
    fontSize:           'فونٹ سائز',
    newPassword:        'نیا پاس ورڈ',
    update:             'اپڈیٹ کریں',
    today:              'آج',
    yesterday:          'کل',
    noResults:          'کوئی صارف نہیں ملا',
    startChat:          'چیٹ شروع کریں',
    profileUpdated:     'پروفائل اپڈیٹ ہو گئی!',
    passwordMismatch:   'پاس ورڈز مطابقت نہیں رکھتے',
    usernameRequired:   'صارف نام ضروری ہے',
    fillAllFields:      'براہ کرم تمام خانے پُر کریں',
    userNotFound:       'صارف نہیں ملا',
    somethingWrong:     'کچھ غلط ہو گیا',
    accountCreated:     'اکاؤنٹ بن گیا! براہ کرم لاگ ان کریں۔',
    search:             'تلاش',
    flowPlaceholder:    'آپ کے ذہن میں کیا ہے؟',
    writeComment:       'تبصرہ لکھیں…',
    activeSessions:     'فعال سیشن',
    changePIN:          'PIN تبدیل کریں',
    darkMode:           'ڈارک موڈ',
    lightMode:          'لائٹ موڈ',
  },

  /* ── Persian (Farsi) ─────────────────────────────────────── */
  fa: {
    dir: 'rtl',
    appName:            'انسان',
    login:              'ورود',
    signup:             'ثبت‌نام',
    welcomeBack:        'به انسان خوش آمدید',
    joinInsan:          'امروز به انسان بپیوندید',
    fullName:           'نام کامل',
    username:           'نام کاربری',
    email:              'ایمیل',
    password:           'رمز عبور',
    confirmPassword:    'تأیید رمز عبور',
    forgotPassword:     'رمز عبور را فراموش کردید؟',
    noAccount:          'حساب کاربری ندارید؟',
    haveAccount:        'قبلاً حساب دارید؟',
    chats:              'چت‌ها',
    channels:           'کانال‌ها',
    groups:             'گروه‌ها',
    typeMessage:        'پیام بنویسید…',
    send:               'ارسال',
    online:             'آنلاین',
    offline:            'اخیراً دیده شده',
    typing:             'در حال تایپ…',
    noChats:            'هنوز چتی وجود ندارد',
    noChatsDesc:        'برای شروع گفتگو کاربران را جستجو کنید',
    noMessages:         'هنوز پیامی وجود ندارد',
    noMessagesDesc:     'سلام بگویید!',
    editProfile:        'ویرایش پروفایل',
    bio:                'بیوگرافی',
    save:               'ذخیره',
    cancel:             'لغو',
    close:              'بستن',
    createChannel:      'ایجاد کانال',
    createGroup:        'ایجاد گروه',
    channelName:        'نام کانال *',
    groupName:          'نام گروه *',
    description:        'توضیحات',
    searchByName:       'جستجو با نام…',
    searchUsers:        'جستجو با @نام‌کاربری یا نام…',
    settings:           'تنظیمات',
    notifications:      'اعلان‌های فشاری',
    enablePush:         'فعال‌سازی اعلان‌های فشاری',
    tapToGrant:         'برای مجوز OS ضربه بزنید',
    msgPreview:         'پیش‌نمایش پیام',
    msgPreviewSub:      'محتوای پیام را در اعلان نشان دهید',
    vibration:          'لرزش',
    vibrationSub:       'لرزش برای پیام‌ها و تماس‌ها',
    testNotif:          'اعلان آزمایشی',
    testNotifSub:       'برای تأیید یک اعلان آزمایشی ارسال کنید',
    calls:              'تماس‌ها',
    callRingtone:       'زنگ تماس',
    callVibrate:        'لرزش تماس',
    callVibrateSub:     'لرزش برای تماس‌های ورودی',
    chat_settings:      'چت',
    enterSend:          'ارسال با Enter',
    enterSendSub:       'برای ارسال پیام Enter را فشار دهید',
    readReceipts:       'تأییدیه خواندن',
    readReceiptsSub:    'نمایش زمان خواندن پیام‌ها',
    typingIndicator:    'نشانگر تایپ',
    typingIndicatorSub: 'نمایش هنگام تایپ کردن',
    autoDownload:       'دانلود خودکار رسانه',
    autoDownloadSub:    'دانلود خودکار تصاویر و فایل‌ها',
    privacy:            'حریم خصوصی',
    lastSeen:           'آخرین بازدید',
    lastSeenSub:        'چه کسی آخرین بازدید شما را ببیند',
    profilePhoto:       'عکس پروفایل',
    profilePhotoSub:    'چه کسی عکس پروفایل شما را ببیند',
    whoCanMsg:          'چه کسی می‌تواند برایم پیام بفرستد',
    whoCanMsgSub:       'محدود کردن شروع گفتگو',
    security:           'امنیت و حساب',
    changePassword:     'تغییر رمز عبور',
    changePasswordSub:  'رمز عبور حساب خود را به‌روز کنید',
    twoFactor:          'احراز هویت دو مرحله‌ای',
    twoFactorSub:       'لایه امنیتی اضافی برای حساب',
    appLock:            'قفل برنامه',
    appLockSub:         'محافظت از برنامه با PIN ۴ رقمی',
    blockedUsers:       'کاربران مسدود شده',
    blockedUsersSub:    'مدیریت حساب‌های مسدود شده',
    deleteAccount:      'حذف حساب من',
    deleteAccountSub:   'حذف دائمی تمام داده‌های شما',
    data:               'داده و ذخیره‌سازی',
    bgData:             'داده پس‌زمینه',
    bgDataSub:          'همیشه روشن — پیام‌ها و تماس‌ها در پس‌زمینه',
    bgSync:             'همگام‌سازی پس‌زمینه',
    bgSyncSub:          'همیشه روشن — همگام‌سازی هنگام بسته بودن برنامه',
    account:            'حساب',
    logout:             'خروج',
    logoutSub:          'خروج از حساب کاربری',
    language:           'زبان',
    languageSub:        'زبان نمایش برنامه',
    appearance:         'ظاهر',
    theme:              'پوسته',
    fontSize:           'اندازه قلم',
    newPassword:        'رمز عبور جدید',
    update:             'به‌روزرسانی',
    today:              'امروز',
    yesterday:          'دیروز',
    noResults:          'کاربری یافت نشد',
    startChat:          'شروع چت',
    profileUpdated:     'پروفایل به‌روز شد!',
    passwordMismatch:   'رمزهای عبور مطابقت ندارند',
    usernameRequired:   'نام کاربری الزامی است',
    fillAllFields:      'لطفاً تمام فیلدها را پر کنید',
    userNotFound:       'کاربر یافت نشد',
    somethingWrong:     'مشکلی پیش آمد',
    accountCreated:     'حساب ایجاد شد! لطفاً وارد شوید.',
    search:             'جستجو',
    flowPlaceholder:    'در ذهن شما چه می‌گذرد؟',
    writeComment:       'یک نظر بنویسید…',
    activeSessions:     'نشست‌های فعال',
    changePIN:          'تغییر PIN',
    darkMode:           'حالت تاریک',
    lightMode:          'حالت روشن',
  },

};

/* ── i18n engine ─────────────────────────────────────────────
   Call I18n.apply(code) to translate the whole UI instantly.
   Elements: data-i18n="key"        → sets textContent
             data-i18n-ph="key"     → sets placeholder
   Also sets document dir (rtl/ltr) and lang attribute.
   ──────────────────────────────────────────────────────────── */
const I18n = {
  locale: 'en',

  t(key) {
    var d = LANG[this.locale] || LANG.en;
    return d[key] !== undefined ? d[key] : (LANG.en[key] !== undefined ? LANG.en[key] : key);
  },

  apply(code) {
    var supported = LANG[code] ? code : 'en';
    var d = LANG[supported];
    this.locale = supported;

    document.documentElement.dir  = d.dir || 'ltr';
    document.documentElement.lang = supported;

    document.querySelectorAll('[data-i18n]').forEach(function(el) {
      var key = el.getAttribute('data-i18n');
      el.textContent = d[key] !== undefined ? d[key] : (LANG.en[key] !== undefined ? LANG.en[key] : key);
    });

    document.querySelectorAll('[data-i18n-ph]').forEach(function(el) {
      var key = el.getAttribute('data-i18n-ph');
      el.placeholder = d[key] !== undefined ? d[key] : (LANG.en[key] !== undefined ? LANG.en[key] : key);
    });
  },
};
